{
 "title": "Salezi | Fnac dashboard",
 "description": "for the Fnac manager <3",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Electronics Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quantity of Electronics",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT Name, Brand, Quantity FROM Electronics",
     "rawQueryText": "SELECT Name, Brand, Quantity FROM Electronics",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "% per Brand",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  brand,\n  COUNT(*) * 100.0 / (SELECT COUNT(*) FROM Electronics) AS percentage\nFROM Electronics\nGROUP BY brand;\n",
     "rawQueryText": "SELECT\n  brand,\n  COUNT(*) * 100.0 / (SELECT COUNT(*) FROM Electronics) AS percentage\nFROM Electronics\nGROUP BY brand;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Books Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Quantity of Books",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT Name, Author, Quantity FROM Books",
     "rawQueryText": "SELECT Name, Author, Quantity FROM Books",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "% per Genre",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  type,\n  COUNT(*) * 100.0 / (SELECT COUNT(*) FROM Books) AS percentage\nFROM Books\nGROUP BY type;\n",
     "rawQueryText": "SELECT\n  type,\n  COUNT(*) * 100.0 / (SELECT COUNT(*) FROM Books) AS percentage\nFROM Books\nGROUP BY type;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "CD Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Quantity of CDs",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT Name, Artist, Quantity FROM Cds",
     "rawQueryText": "SELECT Name, Artist, Quantity FROM Cds",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "% per Style",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  style,\n  COUNT(*) * 100.0 / (SELECT COUNT(*) FROM Cds) AS percentage\nFROM Cds\nGROUP BY style;\n",
     "rawQueryText": "SELECT\n  style,\n  COUNT(*) * 100.0 / (SELECT COUNT(*) FROM Cds) AS percentage\nFROM Cds\nGROUP BY style;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}